"""Session producer: serialize a final RunState into the mining input format."""

from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path
from typing import Any

# The producer owns the corpus schema; the miner imports this and fails fast
# on mismatch (review F4). Bump when the session/record shape changes.
SESSION_SCHEMA_VERSION = 2


def write_session(
    final_state: dict[str, Any],
    metadata: dict[str, Any],
    out_dir: Path,
) -> Path:
    """Write session.jsonl + metadata.json from a finished engine run.

    Each StepRecord becomes one line carrying the exact serve-time renders
    (trajectory + prompt) and the produced output, so the mined corpus
    matches what the engine generated by construction. ``schema_version`` is
    always stamped (caller-supplied value cannot override it).
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    for rec in final_state.get("trajectory", []):
        feedback = asdict(rec.feedback) if rec.feedback is not None else None
        lines.append(
            json.dumps(
                {
                    "step": rec.step,
                    "action": rec.action_name,
                    "target": rec.target_subtask,
                    "trajectory": rec.trajectory_text,
                    "prompt": rec.prompt_text,
                    "output": rec.output_text,
                    "feedback": feedback,
                }
            )
        )
    (out_dir / "session.jsonl").write_text("\n".join(lines) + "\n" if lines else "")
    (out_dir / "metadata.json").write_text(
        json.dumps({**metadata, "schema_version": SESSION_SCHEMA_VERSION})
    )
    return out_dir
